name       : iperf
version    : 3.10.1
release    : 5
source     :
    - https://github.com/esnet/iperf/archive/refs/tags/3.10.1.tar.gz : 6a4bb4d5c124b3fa64dfbda469ab16857ad6565310bcaa3dd8cd32f96c2fc473
license    :
    - BSD-3-Clause
    - MIT
component  : network.util
summary    : A TCP, UDP, and SCTP network bandwidth measurement tool
description: |
    iperf is a tool for active measurements of the maximum achievable bandwidth on IP networks.  It supports tuning of various parameters related to timing, protocols, and buffers. For each test it reports the bandwidth, loss, and other parameters.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
